05/08/21 (18:14:22) | ERROR: Exception while getting cpu frequency!
05/08/21 (18:14:22) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (18:15:24) | ERROR: Exception while getting cpu frequency!
05/08/21 (18:15:24) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (18:16:59) | ERROR: Exception while getting cpu frequency!
05/08/21 (18:16:59) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (18:18:06) | ERROR: Exception while getting cpu frequency!
05/08/21 (18:18:06) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (18:18:06) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
05/08/21 (18:20:09) | ERROR: Exception while getting cpu frequency!
05/08/21 (18:20:09) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (18:20:09) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
05/08/21 (22:29:49) | ERROR: Exception while getting cpu frequency!
05/08/21 (22:29:49) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
05/08/21 (22:29:49) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
06/08/21 (04:46:58) | ERROR: Exception while getting cpu frequency!
06/08/21 (04:46:58) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_1/libexec/lib/python3.9/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
06/08/21 (04:46:58) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
15/11/21 (20:17:38) | ERROR: Exception while getting cpu frequency!
15/11/21 (20:17:38) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
15/11/21 (20:17:38) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
15/11/21 (20:18:48) | ERROR: Exception while getting cpu frequency!
15/11/21 (20:18:48) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
15/11/21 (20:18:48) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
15/11/21 (20:18:51) | ERROR: Exception while getting cpu frequency!
15/11/21 (20:18:51) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
15/11/21 (20:18:51) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
23/12/21 (10:56:39) | ERROR: Exception while getting cpu frequency!
23/12/21 (10:56:39) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/12/21 (10:56:39) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
23/12/21 (10:57:10) | INFO: Loglevel set to INFO
23/12/21 (11:01:44) | ERROR: Exception while getting cpu frequency!
23/12/21 (11:01:44) | ERROR: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3060, in _collect
    if CONFIG.show_cpu_freq and hasattr(psutil.cpu_freq(), "current"):
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/__init__.py", line 1859, in cpu_freq
    ret = _psplatform.cpu_freq()
  File "/opt/homebrew/Cellar/bpytop/1.0.67_2/libexec/lib/python3.10/site-packages/psutil/_psosx.py", line 180, in cpu_freq
    curr, min_, max_ = cext.cpu_freq()
FileNotFoundError: [Errno 2] No such file or directory (originated from sysctlbyname('hw.cpufrequency'))
23/12/21 (11:01:44) | ERROR: Command 'coretemp' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/homebrew/bin/bpytop", line 3188, in _collect_temps
    cores = [max(0, int(x)) for x in subprocess.check_output("coretemp", universal_newlines=True).split()]
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'coretemp' returned non-zero exit status 1.
